package com.project.boongobbang.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum UserType {
    /*반영 필드 목록
     * 청소 빈도 (3 종류)
     * MBTI 의 E/I(외향/내향) 와 T/J(논리/감정)
     * 흡연 유무
     * 야행성 유무
     * => 총 3 * 2 * 2 * 2 * 2 = 48 종류(..)
     */

    CLEAN_1_2_E_T_SMOKER_NOCTURNAL,
    CLEAN_1_2_E_T_SMOKER_DIURNAL,
    CLEAN_1_2_E_T_NON_SMOKER_NOCTURNAL,
    CLEAN_1_2_E_T_NON_SMOKER_DIURNAL,

    CLEAN_1_2_E_F_SMOKER_NOCTURNAL,
    CLEAN_1_2_E_F_SMOKER_DIURNAL,
    CLEAN_1_2_E_F_NON_SMOKER_NOCTURNAL,
    CLEAN_1_2_E_F_NON_SMOKER_DIURNAL,

    CLEAN_1_2_I_T_SMOKER_NOCTURNAL,
    CLEAN_1_2_I_T_SMOKER_DIURNAL,
    CLEAN_1_2_I_T_NON_SMOKER_NOCTURNAL,
    CLEAN_1_2_I_T_NON_SMOKER_DIURNAL,

    CLEAN_1_2_I_F_SMOKER_NOCTURNAL,
    CLEAN_1_2_I_F_SMOKER_DIURNAL,
    CLEAN_1_2_I_F_NON_SMOKER_NOCTURNAL,
    CLEAN_1_2_I_F_NON_SMOKER_DIURNAL,

    CLEAN_3_4_E_T_SMOKER_NOCTURNAL,
    CLEAN_3_4_E_T_SMOKER_DIURNAL,
    CLEAN_3_4_E_T_NON_SMOKER_NOCTURNAL,
    CLEAN_3_4_E_T_NON_SMOKER_DIURNAL,

    CLEAN_3_4_E_F_SMOKER_NOCTURNAL,
    CLEAN_3_4_E_F_SMOKER_DIURNAL,
    CLEAN_3_4_E_F_NON_SMOKER_NOCTURNAL,
    CLEAN_3_4_E_F_NON_SMOKER_DIURNAL,

    CLEAN_3_4_I_T_SMOKER_NOCTURNAL,
    CLEAN_3_4_I_T_SMOKER_DIURNAL,
    CLEAN_3_4_I_T_NON_SMOKER_NOCTURNAL,
    CLEAN_3_4_I_T_NON_SMOKER_DIURNAL,

    CLEAN_3_4_I_F_SMOKER_NOCTURNAL,
    CLEAN_3_4_I_F_SMOKER_DIURNAL,
    CLEAN_3_4_I_F_NON_SMOKER_NOCTURNAL,
    CLEAN_3_4_I_F_NON_SMOKER_DIURNAL,

    CLEAN_MORE_4_E_T_SMOKER_NOCTURNAL,
    CLEAN_MORE_4_E_T_SMOKER_DIURNAL,
    CLEAN_MORE_4_E_T_NON_SMOKER_NOCTURNAL,
    CLEAN_MORE_4_E_T_NON_SMOKER_DIURNAL,

    CLEAN_MORE_4_E_F_SMOKER_NOCTURNAL,
    CLEAN_MORE_4_E_F_SMOKER_DIURNAL,
    CLEAN_MORE_4_E_F_NON_SMOKER_NOCTURNAL,
    CLEAN_MORE_4_E_F_NON_SMOKER_DIURNAL,

    CLEAN_MORE_4_I_T_SMOKER_NOCTURNAL,
    CLEAN_MORE_4_I_T_SMOKER_DIURNAL,
    CLEAN_MORE_4_I_T_NON_SMOKER_NOCTURNAL,
    CLEAN_MORE_4_I_T_NON_SMOKER_DIURNAL,

    CLEAN_MORE_4_I_F_SMOKER_NOCTURNAL,
    CLEAN_MORE_4_I_F_SMOKER_DIURNAL,
    CLEAN_MORE_4_I_F_NON_SMOKER_NOCTURNAL,
    CLEAN_MORE_4_I_F_NON_SMOKER_DIURNAL
}
